//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreduinoNet_DDNS {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoreduinoNet_DDNS.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 没有填写任何参数，将执行默认功能 的本地化字符串。
        /// </summary>
        internal static string argsifempty {
            get {
                return ResourceManager.GetString("argsifempty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NekokeCore @2022 的本地化字符串。
        /// </summary>
        internal static string auther {
            get {
                return ResourceManager.GetString("auther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似   _____                   _       _               _   _      _                      _    
        /// / ____|                 | |     (_)             | \ | |    | |                    | |   
        ///| |     ___  _ __ ___  __| |_   _ _ _ __   ___   |  \| | ___| |___      _____  _ __| | __
        ///| |    / _ \| &apos;__/ _ \/ _` | | | | | &apos;_ \ / _ \  | . ` |/ _ \ __\ \ /\ / / _ \| &apos;__| |/ /
        ///| |___| (_) | | |  __/ (_| | |_| | | | | | (_) | | |\  |  __/ |_ \ V  V / (_) | |  |   &lt; 
        /// \_____\___/|_|  \___|\__,_|\__,_|_|_| |_|\___/  |_| \_|\ [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string banner {
            get {
                return ResourceManager.GetString("banner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 欢迎使用Coreduino Network DDNS更新工具
        ///--v  或  调试        开启debug输出
        ///-h 或  帮助           获取帮助
        ///-u 或  更新           手动更新
        ///-c 或  查询           查询当前的公网IP 的本地化字符串。
        /// </summary>
        internal static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version 1.0.0 的本地化字符串。
        /// </summary>
        internal static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似   _____ _____ _______   _   _      _                      _    
        /// / ____/ ____|__   __| | \ | |    | |                    | |   
        ///| |   | |       | |    |  \| | ___| |___      _____  _ __| | __
        ///| |   | |       | |    | . ` |/ _ \ __\ \ /\ / / _ \| &apos;__| |/ /
        ///| |___| |____   | |    | |\  |  __/ |_ \ V  V / (_) | |  |   &lt; 
        /// \_____\_____|  |_|    |_| \_|\___|\__| \_/\_/ \___/|_|  |_|\_\ 的本地化字符串。
        /// </summary>
        internal static string specialbanner1 {
            get {
                return ResourceManager.GetString("specialbanner1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SpecialVersion 1.0.0 For CCT Server 的本地化字符串。
        /// </summary>
        internal static string specialinfo1 {
            get {
                return ResourceManager.GetString("specialinfo1", resourceCulture);
            }
        }
    }
}
